### ISSUE TITLE
Comparing to strings

### ISSUE THREAD

**Issue by tolomea** [nshafer/django-hashid-field#14]
There are a bunch of situations where it would be convenient if str(hashid) == hashid was True.
I was wondering if there was a particular reason why this is not supported currently?

**Comment by nshafer** [comment]
No reason other than I just hadn't implemented it. I just added some extra cases in __eq__ of the Hashid class. I'll push it in the next version.

**Comment by tolomea** [comment]
I took a look at the change, I'm not sure it's safe. Isn't there a rule somewhere that says if a==b then hash(a) must equal hash(b)?

**Comment by nshafer** [comment]
I'm not exactly following you... this is true? `a == b` and `hash(a) == hash(b)` when `a = Hashid(123)` and `b = Hashid(123)`. I added a test that checks that it is. I just now added extra support for comparing a Hashid to either ints or strings, and for it to Just Work. It's specifically in commit 60448213d07288563ad69c97e5f519207bc5a75a. So is there something I'm missing?

**Comment by tolomea** [comment]
So str(Hashid(123)) == Hashid(123), but hash(str(Hashid(123))) !=
hash(Hashid(123))

I'm not sure how much of an issue this is, but it does mean that
str(Hashid(123)) in {Hashid(123)} is probably normally False but once in a
while True, as they compare True but usually have different hashes.

The only easy fix that comes to mind is to only compare with strings not
int's and to use the hash of the string as the hash of the Hashid

**Comment by tolomea** [comment]
Or make Hashid's not hashable so they can't be inserted into sets and
dicts. Simply removing the __hash__ function will do that.

**Comment by nshafer** [comment]
Well, I can't remove `__hash__` as it's required to support functionality in Django, such as `prefetch_related` (which puts ids in a set).

Reading through [the python data model docs](https://docs.python.org/3/reference/datamodel.html#object.__hash__) for `__hash__`, it says, "The only required property is that objects which compare equal have the same hash value".

So, I have removed the integer equality and changed `__hash__` to return `hash(self.hashid)` so that `hash(Hashid(123)) == hash(str(Hashid(123)))`. It also takes into account the other things that make a Hashid unique, such as the salt, alphabet and min_length, so that `Hashid(123) != Hashid(123, salt="asdf")`.

Commit 1534c8813024122840dbdec7f82806c88c7795fc

I think with this change, overall it's much robust and fits the Python Data model better. Unless you can think of another case? Thanks a ton for your help... this is exactly why I released this as open source. =)

**Comment by tolomea** [comment]
That all sounds good, thanks

**Comment by nshafer** [comment]
These changes are live in 1.3.0.
