### ISSUE TITLE
HashidAutoField auto-increments just like an AutoField

### ISSUE THREAD

**Issue by v10s** [nshafer/django-hashid-field#43]
https://github.com/nshafer/django-hashid-field#hashid-auto-field
It's a little confusing u said that "Along with HashidField there is also a HashidAutoField that works in the same way, but that auto-increments just like an AutoField"
So due it means that successive hash values will have unit difference which will be the same in all cases.
I am expecting it won't be like that but it read up the same.
And if so will in not pose a security concern.
M a little confused.

**Comment by nshafer** [comment]
An AutoField is a built-in Django field that is added to any model as `id` that you don't specifically set a primary key on. It's actual implementation depends on your database, such as it's a `serial` field with a sequence on Postgres, or an integer field with `autoincrement` set in MySQL. Since HashidAutoField just obscures the underlying integer by inheriting directly from AutoField, it works the same way. Each new row that's added without an explicit value for the HashidAutoField will generate the next ID in the database, and the module will just obscure it with a unique hashids value. Hopefully that helps.

**Comment by v10s** [comment]
Yeah, it really did thanks.
