### ISSUE TITLE
Substitute a CharField with a HashidAutoField

### ISSUE THREAD

**Issue by bluesurfer** [nshafer/django-hashid-field#6]
I am currently using the `hashids`library to generate a friendly ID from the object primary key. Something similar to the following example taken from [djangosnippets](https://djangosnippets.org/snippets/1249/)

```
 def save(self, *args, **kwargs):
    super(MyModel, self).save(*args, **kwargs)

    # Populate the invoice_id if it is missing
    if self.id and not self.invoice_id:
        self.invoice_id = friendly_id.encode(self.id)
        super(MyModel, self).save(*args, **kwargs)
```
That is quite an ugly solution. Plus I made the same mistake described in #1. I would like to adopt this package but I have two requirements:

1. Keep the old hashids stored in a `CharField`
2. Instances of different models must have different hashids

Is that possible? To avoid collision with old hashids I could set a different length for the new ones but I don't know how to properly integrate it.

**Comment by nshafer** [comment]
One solution would be to [drop in HashidAutoField](https://github.com/nshafer/django-hashid-field#hashid-auto-field) on 'id' for this model. Then lookups by either the old integer will work (ALLOW_INT is true by default), or by the new hashid value that gets generated will work. Then you can remove your custom `save()` function, and instead do lookups with something like `Invoice.objects.get(Q(invoice_id='TTH9R') | Q(id='TTH9R'))`. Not great as this requires modifying all of your lookups.

Another solution would be to create a new Field based on HashidFieldMixin and CharField, like this:

```python
from hashid_field.field import HashidFieldMixin

class HashidExistingCharField(HashidFieldMixin, models.CharField):
    description = "A Hashids obscured CharField that may have existing non-compliant strings"

    def from_db_value(self, value, expression, connection, context):
        try:
            return super(HashidCharField, self).from_db_value(value, expression, connection, context)
        except ValueError:
            return value

    def get_prep_value(self, value):
        try:
            return super(HashidCharField, self).get_prep_value(value)
        except TypeError:
            return value

```

Then change `invoice_id` to use this field instead. You'll still need the custom save() to set invoice_id, but all new rows will use Hashids instead of friendly_id. I did some preliminary testing with this and it seems to work in this case. I thought about adding official support for HashidCharField, but it's application seems very niche, and doesn't even really solve your issue.

I created a branch with some proof-of-concept code:
- [HashidCharFIeld](https://github.com/nshafer/django-hashid-field/blob/hashidcharfield/hashid_field/field.py#L119)
- [HashidExistingCharField](https://github.com/nshafer/django-hashid-field/blob/hashidcharfield/hashid_field/field.py#L140)
- [implementation](https://github.com/nshafer/django-hashid-field/blob/hashidcharfield/sandbox/library/models.py#L24)

Other than that, I can't think of any way to remove your custom `save()` (that ends up creating two queries on every save of new objects), without causing issues elsewhere or dropping all support for your old IDs, which would probably break existing URLs. Honestly, your best bet is probably to just leave this one as is.
