### ISSUE TITLE
`icontains` filtering is not working

### ISSUE THREAD

**Issue by Arti3DPlayer** [nshafer/django-hashid-field#62]
`Model.objects.filter(id__icontains='Vn6N7n4')` is working fine. But if I `lower()` string this is not working. Same with `Model.objects.filter(id__icontains='V')`

**Comment by nshafer** [comment]
This is working as intended, actually. The actual value of "Vn6N7n4" is stored as an integer in the database, not a string. So when doing a lookup, the lookup code has to decode the given string into an integer to find the matching row. And since every character used in the `alphabet` is significant, case included, "vn6n7n4" is a very different number (if valid at all.) Also, we can't decode just "V" into an integer either. So why support these lookups at all, I'm sure you're asking. It's a trade-off so that the default django admin works without throwing errors. If you add a Hashid*Field to `search_fields` in the django admin, by default it does an `__icontains` lookup. So I decided to support this lookup (and might as well support `__iexact` and `__contains` for good measure) but it functions exactly the same as a normal non-suffixed search (`myfield="Vn6N7n4"`) or an exact lookup (`myfield__exact="Vn6N7n4"`). This is briefly mentioned in the README, but could possibly use more explanation.

**Comment by Arti3DPlayer** [comment]
@nshafer Thanks for your answer. The use-case for this is a search page where we need to ignore case sensitive and as I thought maybe allow to search results that contain substring in ID

**Comment by nshafer** [comment]
I'm not sure exactly what you're trying to do, or what the implementation details of your app are, but I would be very careful with trying to do what you describe with the default alphabet. If there is an object with a Hashid of "ABC" and you allow a user to type in "abc" to match it, there might be very different records with "Abc", "ABc", "ABC", "abc", "abC", "aBC", "AbC", etc. The user could be matched with the wrong row or possibly be returned multiple rows that happen to match.

If you are set on making it case insensitive to allow for lazy human input, then you need to use a limited alphabet that includes only lowercase or only uppercase letters, such as `alphabet="abcdefghijklmnopqrstuvwxyz1234567890"` which in that case, you can just do a lookup of `MyModel.objects.filter(id=input_from_user.lower())` to ignore case.

Doing partial searches is still not possible with that solution, but that cause even more invalid matches and weird undefined behavior as trying to match `__icontains="V"` could result in hundreds of records that have no relationship with each other except the fact that their IDs happened to encode to a Hashid that included the character "V". It would be like saying, "give me all rows that happen to have a 1 in their ID."

As for annotating, even if you could do that, every query would require iterating every row of the table (rowscan) to create a string representations of every ID, so it would perform horribly and scale at O(n).

If you really require this functionality for some reason that I can't fathom, then you could store the string representation in another column on save.

```python
class MyModel(models.Model):
    id = HashidAutoField(primary_key=True)
    id_str = models.CharField(max_length=25, blank=True)

    def save(self, *args, **kwargs):
        self.id_str = str(self.id)
        super().save(*args, **kwargs)
```

And then you can do string-compatible lookups on the resulting Hashid string, such as `MyModel.objects.filter(id_str__icontains="abcdefg")`.

I'm curious exactly what you're trying to solve if you don't mind expanding on your use-case.

**Comment by Arti3DPlayer** [comment]
@nshafer Great, I guess I will use one of your suggestions. Thanks again
